s = 'ПОЛСЯПКОЗКПКЯСОППЛООЛСОПЛПКЛКППСППЗКЯПЗСООЯППОЛСЛСПОПЛКСОЯЛПСОЛПОКЛПООПОЯЛПСПОЛПЗ'
a = []
print(len(s), 'всего')
for i in s:
    if i not in a:
        a.append(i)
p = s.count('П')
o = s.count('О')
l = s.count('Л')
c = s.count('С')
ya = s.count('Я')
k = s.count('К')
z = s.count('З')
print('количество:')
print('p', p)
print('o', o)
print('l', l)
print('c', c)
print('ya', ya)
print('k', k)
print('z', z)
print()
print('частота:')
print('p', p/81)
print('o', o/81)
print('l', l/81)
print('c', c/81)
print('ya', ya/81)
print('k', k/81)
print('z', z/81)
print()
print('процент золотых рыбок:', z/81*100)
